<?php

/**
 * Created by youyi000.
 * DateTime: 2017/4/12 20:40
 * Describe：
 */
class WebUser extends CWebUser
{

    public $user;

    public function init()
    {
        if (Mod::app() instanceof CConsoleApplication)
        {
            $this->id =0;
            return false;
        }
        //$this->loginUrl=array('/site/login');
        $this->authTimeout=3600*10; //设置Cookies保持自动登录的时长
        parent::init();
    }

    public function __construct()
    {
        $this->allowAutoLogin=true;
        $this->setStateKeyPrefix("oil_ao389kd9433");
        $this->loginRequiredAjaxResponse="请先登录";
    }


    public function login($identity,$duration=0)
    {
        $this->user=$identity->user;
        return parent::login($identity,$duration);
    }

    protected function beforeLogin($id, $states, $fromCookie)
    {
        if($fromCookie)
        {
            $secret=Utility::hGetCache(SystemUser::RedisSessionKey,$id);
            if($states["token"]!=$secret)
                return false;
        }

        return parent::beforeLogin($id, $states, $fromCookie); // TODO: Change the autogenerated stub
    }

    /**
     * 当前用户是否是游客身份，增加了加密串的判断，暂时不启用
     * @return bool
     */
    /*public function getIsGuest()
    {
        $id=$this->getState('__id');
        if($id===null)
            return true;
        $secret=Utility::hGetCache(SystemUser::RedisSessionKey,$id);
        if($this->getState("token")!=$secret)
            return true;
        else
            return false;
    }*/

    protected function afterLogin($fromCookie)
    {
        parent::afterLogin($fromCookie);

        $this->getUser();
        SystemUser::setFormattedRightCodes($this->user["user_id"],$this->user["right_codes"]);
        SystemUser::updateLoginInfo($this->user["user_id"]);
    }

    public function getUser()
    {
        if(empty($this->user))
            $this->user=SystemUser::model()->findByPk(Mod::app()->user->id);
    }
}