<?php
/**
 * Created by youyi000.
 * DateTime: 2017/11/8 15:47
 * Describe：
 */

Mod::import("system.components.weixin.CWeixinComp");

class WXCorporation extends  CWeixinComp
{

    public $agent=array();

    /*
     * 车友帮
     * CorpID：ww0f15b7e86e3ad77c
        AgentId:1000002
        Secret:Ys78-X8qxCwEtIHynNYJzTEMX0B4HDOkSPBeV58pLZg*/
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }


    /**
     * 添加企业用户
     * @param $user
     * @return bool
     */
    public function addUser($user)
    {
        /*{
            "userid": "zhangsan",
           "name": "张三",
           "department": [1, 2],
           "position": "产品经理",
           "mobile": "15913215421",
           "gender": "1",
           "email": "zhangsan@gzdev.com",
           "weixinid": "zhangsan4dev",
           "avatar_mediaid": "2-G6nrLmr5EC3MNb_-zL1dDdzkd0p7cNliYu9V5w7o8K0",
           "extattr": {"attrs":[{"name":"爱好","value":"旅游"},{"name":"卡号","value":"1234567234"}]}
        }*/

        $data = array(
            'userid' => $user->user_id,
            'name' => $user->name,
            //"department"=>"[1]",
            "department"=>array(1),
        );

        if (!empty($user->weixin))
            $data["weixinid"] = $user->weixin;
        if (!empty($user->email))
            $data["email"] = $user->email;
        if (!empty($user->phone))
            $data["mobile"] = $user->phone;

        try
        {
            //var_dump($data);
            $res=$this->call('user', 'create', self::cn_json_encode($data));
            var_dump($res);
            $res = json_decode($res);

            if ($res->errcode != 0)
            {
                Mod::log(sprintf('addUser error,errcode:%s,errmsg:%s,user_id:%s', $res->errorcode, $res->errormsg, $user->user_id), 'error');
                //throw new BusinessException('新增用户失败');
                return false;
            }
            return true;
        }
        catch (Exception $e)
        {
            Mod::log("weiXin addUser error: ".$e->getMessage().", userId: ".$user->user_id,"error");
            return false;
        }

    }

    /**
     * 更新用户
     * @param $userId
     * @param $params
     * @return bool
     */
    public function updateUser($userId,$params)
    {
        $data = array(
            'userid' => $userId,
        );

        if (!empty($params["name"]))
            $data["name"] = $params["name"];

        if (!empty($params["weixinid"]))
            $data["weixinid"] = $params["weixinid"];

        if (!empty($params["email"]))
            $data["email"] = $params["email"];

        if (!empty($params["mobile"]))
            $data["mobile"] = $params["mobile"];

        /*if($user->attributeIsModified("name"))
            $data["name"]=$user->name;

        if($user->attributeIsModified("weixin"))
            $data["weixinid"]=$user->weixin;

        if($user->attributeIsModified("email"))
            $data["email"] = $user->email;
        if($user->attributeIsModified("phone"))
            $data["mobile"] = $user->phone;*/

        if(count($data)==1)
            return true;

        try
        {
            $res=$this->call('user', 'update', self::cn_json_encode($data));
            //var_dump($res);
            $res = json_decode($res);
            if ($res->errcode != 0)
            {
                Mod::log(sprintf('updateUser error,errcode:%s,errmsg:%s,user_id:%s', $res->errorcode, $res->errormsg, $user->user_id), 'error');
                //throw new BusinessException('新增用户失败');
                return false;
            }
            return true;
        }
        catch (Exception $e)
        {
            Mod::log("weiXin updateUser error: ".$e->getMessage().", userId: ".$user->user_id,"error");
            return false;
        }
    }

    public function getDepartments()
    {
        //$res=$this->call('department', 'list');
        $token = $this->getToken();
        $url ="https://qyapi.weixin.qq.com/cgi-bin/department/list?access_token=".$token; //sprintf(self::CALL_BASE_URL,$type,$func)."?access_token=".$token;

        $ret = Mod::app()->curl->get($url);
        var_dump($ret);
    }

    public function getUsers()
    {
        $token = $this->getToken();
        $url ="https://qyapi.weixin.qq.com/cgi-bin/user/get?access_token=".$token."&userid=2"; //sprintf(self::CALL_BASE_URL,$type,$func)."?access_token=".$token;

        $ret = Mod::app()->curl->get($url);
        var_dump($ret);

    }

}