<?php
/**
 * Created by youyi000.
 * DateTime: 2017/12/21 10:11
 * Describe：
 */

class ZPagination extends CPagination
{

    const DEFAULT_PAGE_SIZE = 25;

    /**
     * @var string name of the GET variable storing the page size. Defaults to 'pageSize'.
     */
    public $pageSizeVar='pageSize';

    public function getPageSize()
    {
        if(isset($_GET[$this->pageSizeVar]))
        {
            $size = (int)$_GET[$this->pageSizeVar];
            $this->setPageSize($size);
        }
        return parent::getPageSize(); // TODO: Change the autogenerated stub
    }

    /**
     * @param integer $value number of items in each page
     */
    public function setPageSize($value)
    {
        if($value<=0)
            $value=self::DEFAULT_PAGE_SIZE;
        parent::setPageSize($value);
    }

}