<?php

/**
 * Created by youyi000.
 * DateTime: 2016/12/14 10:02
 * Describe：
 */
class CheckExtraLog extends BaseActiveRecord
{

    public $items=array();

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 't_check_extra_log';
    }

    protected function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->items=json_decode($this->content,true);
    }



}