<?php
/**
 * Created by youyi000.
 * DateTime: 2018/8/13 19:33
 * Describe：
 *      时间对象
 */

namespace ddd\Common\Domain\Value;


class DateTime extends \DateTime
{
    /**
     * 格式化时间
     * @param string $format
     * @return string
     */
    public function format($format="Y-m-d H:i:s")
    {
        return parent::format($format); // TODO: Change the autogenerated stub
    }

    /**
     * 返回时间字符串
     * @param string $format
     * @return string
     */
    public function toDateTime($format="Y-m-d H:i:s")
    {
        return $this->format($format);
    }

    /**
     * 返回日期字符串
     * @param string $format
     * @return string
     */
    public function toDate($format="Y-m-d")
    {
        return $this->format($format);
    }

    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->format();
    }


}